default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: /tmp
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: administrate_development

test:
  <<: *default
  database: administrate_test
